### ISSUE TITLE
Caused by: javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default

### ISSUE THREAD

**Issue by Nandaram1994** [OpenLiberty/start.openliberty.io#147]
Hi,
I want to deploy the upgrade jdk11 application from jdk8 to the open liberty server( openliberty-22.0.0.11 )  while deploying the application then I am getting the below error. Can anyone please help me out? It is working fine with the WebLogic server.

**web.xml**

<?xml version="1.0" encoding="UTF-8"?>

<web-app id="mdms-datahub" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" version="2.5" 
	metadata-complete="true">
<resource-ref id="ResourceRef_SpringPoolTimerManager">
		<description>Spring Thread Pool WorkManager</description>
		<res-ref-name>tm/default</res-ref-name>
		<res-type>commonj.timers.TimerManager</res-type>
		<res-auth>Container</res-auth>
		<res-sharing-scope>Unshareable</res-sharing-scope>
	</resource-ref>

**ibm-web-bnd.xml**

<?xml version="1.0" encoding="UTF-8"?>
    <web-bnd xmlns="http://websphere.ibm.com/xml/ns/javaee"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://websphere.ibm.com/xml/ns/javaee http://websphere.ibm.com/xml/ns/javaee/ibm-web-bnd_1_0.xsd"
     version="1.0">
     
     <resource-ref name="tm/default" binding-name="tm/default"/>
</web-bnd>

**Spring.xml**

	<bean id="dseReadEventRequeueTimerManager"
		class="org.springframework.scheduling.commonj.TimerManagerFactoryBean"
		p:resourceRef="true" p:timerManagerName="tm/default">
		<property name="scheduledTimerListeners">
			<list>
				<ref bean="dseReadEventRequeueScheduledListener" />
			</list>
		</property>
	</bean>

[12/19/22, 11:14:08:699 IST] 00000036 com.ibm.ws.webcontainer.webapp                               I SRVE0292I: Servlet Message - [services]:.Initializing Spring root WebApplicationContext
[12/19/22, 11:16:45:965 IST] 00000036 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "org.springframework.beans.factory.access.BootstrapException: Unable to return specified BeanFactory instance: factory key [server.context], from group with resource name [classpath*:beanRefContext.xml]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server.context': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated 1341" at ffdc_22.12.19_11.16.45.0.log
[12/19/22, 11:16:45:969 IST] 00000036 com.ibm.ws.webcontainer.webapp                               E SRVE0283E: Exception caught while initializing context: org.springframework.beans.factory.access.BootstrapException: Unable to return specified BeanFactory instance: factory key [server.context], from group with resource name [classpath*:beanRefContext.xml]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server.context': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:404)
	at org.springframework.web.context.ContextLoader.loadParentContext(ContextLoader.java:563)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:322)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at com.ecologic.components.server.core.spring.EAComponentsContextLoaderListener.contextInitialized(EAComponentsContextLoaderListener.java:25)
	at com.ecologic.components.server.security.spring.SecurityInitializingContextLoaderListener.contextInitialized(SecurityInitializingContextLoaderListener.java:34)
	at com.ecologic.components.server.security.spring.SOAPWebServicesSecurityInitializingContextLoaderListener.contextInitialized(SOAPWebServicesSecurityInitializingContextLoaderListener.java:253)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2446)
	at com.ibm.ws.webcontainer31.osgi.webapp.WebApp31.notifyServletContextCreated(WebApp31.java:510)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1044)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6684)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:472)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1188)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$100(WebContainer.java:111)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:985)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'server.context': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:177)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1640)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1086)
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:396)
	... 21 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'recurringPasswordConversion' defined in class path resource [Spring-Core-Timer.xml]: Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:105)
	at com.ecologic.server.ServerApplicationContextFactory.getObject(ServerApplicationContextFactory.java:157)
	at com.ecologic.server.ServerApplicationContextFactory.getObject(ServerApplicationContextFactory.java:37)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:170)
	... 27 more
Caused by: javax.naming.NameNotFoundException: Intermediate context does not exist: tm/default
	at com.ibm.ws.jndi.internal.ContextNode.getTargetNode(ContextNode.java:125)
	at com.ibm.ws.jndi.internal.ContextNode.lookup(ContextNode.java:211)
	at com.ibm.ws.jndi.internal.WSContext.lookup(WSContext.java:308)
	at com.ibm.ws.jndi.WSContextBase.lookup(WSContextBase.java:61)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:149)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at org.springframework.jndi.JndiTemplate$1.doInContext(JndiTemplate.java:155)
	at org.springframework.jndi.JndiTemplate.execute(JndiTemplate.java:87)
	at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:152)
	at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:179)
	at org.springframework.jndi.JndiLocatorSupport.lookup(JndiLocatorSupport.java:104)
	at org.springframework.scheduling.commonj.TimerManagerAccessor.afterPropertiesSet(TimerManagerAccessor.java:104)
	at org.springframework.scheduling.commonj.TimerManagerFactoryBean.afterPropertiesSet(TimerManagerFactoryBean.java:81)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 41 more

**Comment by scottkurz** [comment]
Hi, I just replied to this same question posted on https://gitter.im/OpenLiberty/developer-experience.   (I realize you might have turned here after not getting a response there) asking what features you'd enabled in server.xml.  (Maybe you need to enable `<feature>jndi-1.0</feature>` ?). 

Another idea would be to open a StackOverflow question with an 'open-liberty' or 'websphere-liberty' tag (those tags are monitored by the Liberty team).

Since this doesn't seem like a good fit for the current repo (the Open Liberty starter app), I'm going to close this issue.  But please do continue in the Gitter or StackOverflow forums.
